In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/faulty_records.csv')

In [3]:
df

,timestamp,passenger_count,trip_distance,total_amount,humidity,pressure,temperature,weather_description,wind_direction,wind_speed
0,1042574400,1,0.00,2.30,NaN,NaN,NaN,NaN,NaN,NaN
1,978760800,1,0.00,3.80,NaN,NaN,NaN,NaN,NaN,NaN
2,978307200,1,0.00,3.80,NaN,NaN,NaN,NaN,NaN,NaN
3,1042567200,1,0.00,2.30,NaN,NaN,NaN,NaN,NaN,NaN
4,1516453200,1,0.00,6.30,NaN,NaN,NaN,NaN,NaN,NaN
5,1042502400,1,0.00,2.30,NaN,NaN,NaN,NaN,NaN,NaN
6,1042574400,1,0.00,2.30,NaN,NaN,NaN,NaN,NaN,NaN
7,978760800,1,0.00,3.80,NaN,NaN,NaN,NaN,NaN,NaN
8,978307200,1,0.00,3.80,NaN,NaN,NaN,NaN,NaN,NaN
9,1042567200,1,0.00,2.30,NaN,NaN,NaN,NaN,NaN,NaN
10,1454950800,32735,-3337066.38,317594.34,88.0,1009.0,273.74,fog,40.0,3.0
11,1516453200,1,0.00,6.30,NaN,NaN,NaN,NaN,NaN,NaN
12,1042502400,1,0.00,2.30,NaN,NaN,NaN,NaN,NaN,NaN
13,1230757200,5,0.61,6.80,NaN,NaN,NaN,NaN,NaN,NaN
14,1510686000,32606,53850.26,330192.71,NaN,NaN,NaN,NaN,NaN,NaN
15,1509800400,31829,47248.07,278149.54,NaN,NaN,NaN,NaN,NaN,NaN
16,1511528400,22418,34495.81,183275.81,NaN,NaN,NaN,NaN,NaN,NaN
17,1514401200,26229,41574.37,256100.36,NaN,NaN,NaN,NaN,NaN,NaN
18,1513206000,28219,59548.72,315406.60,NaN,NaN,NaN,NaN,NaN,NaN
19,1513155600,28924,43467.74,288961.04,NaN,NaN,NaN,NaN,NaN,NaN
20,1511254800,24902,38652.60,248761.59,NaN,NaN,NaN,NaN,NaN,NaN
21,1510185600,13063,26822.54,134756.12,NaN,NaN,NaN,NaN,NaN,NaN
22,1512352800,2807,6243.75,27939.51,NaN,NaN,NaN,NaN,NaN,NaN
23,1512201600,14867,26590.00,132903.25,NaN,NaN,NaN,NaN,NaN,NaN
24,1511708400,25656,49739.72,259919.38,NaN,NaN,NaN,NaN,NaN,NaN
25,1509418800,2120,5005.94,22758.51,NaN,NaN,NaN,NaN,NaN,NaN
26,1510048800,23660,39629.37,249323.23,NaN,NaN,NaN,NaN,NaN,NaN
27,1509663600,26880,55448.92,285389.48,NaN,NaN,NaN,NaN,NaN,NaN
28,1512712800,12825,28450.57,136669.08,NaN,NaN,NaN,NaN,NaN,NaN
29,1510304400,25917,42189.19,264380.55,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1601,1509793200,30023,42075.12,244295.53,NaN,NaN,NaN,NaN,NaN,NaN
1602,1511560800,22839,34746.94,188304.34,NaN,NaN,NaN,NaN,NaN,NaN
1603,1511010000,34456,52024.73,308612.97,NaN,NaN,NaN,NaN,NaN,NaN
1604,1512885600,4748,15922.75,66145.12,NaN,NaN,NaN,NaN,NaN,NaN
1605,1510293600,12880,28136.81,135535.10,NaN,NaN,NaN,NaN,NaN,NaN
1606,1513335600,27997,44276.86,289746.02,NaN,NaN,NaN,NaN,NaN,NaN
1607,1509786000,23069,35999.18,201249.74,NaN,NaN,NaN,NaN,NaN,NaN
1608,1511060400,15852,29025.95,143638.03,NaN,NaN,NaN,NaN,NaN,NaN
1609,1511420400,8028,16859.93,80482.19,NaN,NaN,NaN,NaN,NaN,NaN
1610,1514682000,13302,23889.70,117711.22,NaN,NaN,NaN,NaN,NaN,NaN
1611,1513929600,22127,34284.01,196193.66,NaN,NaN,NaN,NaN,NaN,NaN
1612,1510963200,28187,50798.00,278480.86,NaN,NaN,NaN,NaN,NaN,NaN
1613,1512788400,12788,24835.33,121024.13,NaN,NaN,NaN,NaN,NaN,NaN
1614,1514466000,29251,43597.16,258980.61,NaN,NaN,NaN,NaN,NaN,NaN
1615,1509580800,13137,28160.94,137069.80,NaN,NaN,NaN,NaN,NaN,NaN
1616,1512450000,4980,13370.33,60037.67,NaN,NaN,NaN,NaN,NaN,NaN
1617,1510365600,17218,30350.38,155501.53,NaN,NaN,NaN,NaN,NaN,NaN
1618,1512039600,24482,40775.89,263838.35,NaN,NaN,NaN,NaN,NaN,NaN
1619,1510934400,24499,45644.52,294232.53,NaN,NaN,NaN,NaN,NaN,NaN
1620,1514613600,4133,12836.52,53113.23,NaN,NaN,NaN,NaN,NaN,NaN
1621,1511802000,26329,46434.84,289479.81,NaN,NaN,NaN,NaN,NaN,NaN
1622,1514545200,24025,35407.67,204584.20,NaN,NaN,NaN,NaN,NaN,NaN
1623,1512838800,32300,49087.44,298432.08,NaN,NaN,NaN,NaN,NaN,NaN
1624,1514055600,24212,33317.46,193196.77,NaN,NaN,NaN,NaN,NaN,NaN
1625,1521417600,1,1.78,14.30,NaN,NaN,NaN,NaN,NaN,NaN
1626,1514599200,11271,19930.04,98218.19,NaN,NaN,NaN,NaN,NaN,NaN
1627,1511175600,22612,35099.73,219266.41,NaN,NaN,NaN,NaN,NaN,NaN
1628,1510938000,29153,50998.55,330402.18,NaN,NaN,NaN,NaN,NaN,NaN
1629,1510077600,34722,52070.81,349486.47,NaN,NaN,NaN,NaN,NaN,NaN
1630,1514350800,3355,9940.11,41995.06,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_spacy = pd.read_pickle('data/cleaned_data_spacy.p')

In [8]:
df_spacy.weather_description.unique()

array(['sky is clear', 'overcast clouds', 'haze', 'mist', 'few clouds',
       'broken clouds', 'moderate rain', 'drizzle', 'scattered clouds',
       'light rain', 'light intensity drizzle', 'heavy intensity rain',
       'thunderstorm', 'fog', 'light snow', 'snow', 'freezing rain',
       'proximity thunderstorm', 'heavy snow', 'dust',
       'thunderstorm with rain', 'thunderstorm with light drizzle',
       'thunderstorm with light rain', 'heavy intensity drizzle', 'sand',
       'smoke', 'thunderstorm with heavy rain',
       'proximity thunderstorm with rain', 'heavy thunderstorm',
       'squalls', 'proximity thunderstorm with drizzle', 'shower rain',
       'light intensity shower rain', 'sand/dust whirls'], dtype=object)

In [9]:
test_phrase_1 = 'thunderstorm with light drizzle'
test_phrase_2 = 'thunderstorm with light rain'
test_phrase_3 = 'sky is clear'

In [13]:
vec_1 = df_spacy[df_spacy['weather_description'] == test_phrase_1]['weather_vec'].values[0]
vec_2 = df_spacy[df_spacy['weather_description'] == test_phrase_2]['weather_vec'].values[0]
vec_3 = df_spacy[df_spacy['weather_description'] == test_phrase_3]['weather_vec'].values[0]

In [14]:
import numpy as np

In [16]:
np.dot(vec_1, vec_2)

-0.3303361

In [17]:
np.dot(vec_2, vec_3)

-0.15964437

In [20]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [25]:
def get_spacy_vec(text):
    doc = nlp(text)
    return doc.vector/doc.vector_norm

In [26]:
vec_1 = get_spacy_vec('thunderstorm with light drizzle')
vec_2 = get_spacy_vec('thunderstorm with light rain')
vec_3 = get_spacy_vec('sky is clear')

In [28]:
np.dot(vec_1, vec_2)

0.9502595

In [29]:
np.dot(vec_1, vec_3)

0.47861218